apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argocd-server-ingress
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
    - host: argocd.mdvorak.org
      http:
        paths:
          - backend:
              serviceName: argocd-server
              servicePort: http
