apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: &name argocd-server-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
    - host: &host argocd.mdvorak.org
      http:
        paths:
          - backend:
              serviceName: argocd-server
              servicePort: http
  tls:
    - hosts:
        - *host
      secretName: *name
