connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: bde380bd65bae9ef622e
      clientSecret: $dex.github.clientSecret
      orgs:
        - name: mdvorak-cloud
          teams:
            - operators
