apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v1.7.6/manifests/install.yaml
  - argo-ingress.yaml

# Custom config
configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - url=https://argocd.mdvorak.org
      - admin.enabled=false
      - statusbadge.enabled=true
    files:
      - repository.credentials=repository-credentials.yaml
      - dex.config=dex-config.yaml

  - name: argocd-rbac-cm
    behavior: merge
    literals:
      - policy.default=role:readonly
    files:
      - policy.csv

patchesStrategicMerge:
  - skip-argocd-secret.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-application-controller
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/command/-
        value: "--app-resync"
      - op: add
        path: /spec/template/spec/containers/0/command/-
        value: "300"
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: "1"
            memory: 1024Mi
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-server
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/command/-
        value: "--insecure"
