name: Render
on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - .github/dependabot.yaml
      - .github/workflow/version.yaml

jobs:
  render:
    name: Render
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1.5.2
        with:
          kustomize-version: "3.8.x"

      - name: Render install.yaml
        run: |
          kustomize build source/ > install.yaml

      - uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: "[bot] rendered install.yaml"
          file_pattern: install.yaml
